# Copyright (c) 2013, AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Import('SmartHome_env')

if SmartHome_env.has_key('_ALLJOYN_JAVA_'):
    SmartHome_env.Append(JAVACLASSPATH = [ str(SmartHome_env.File('$DISTDIR/java/jar/alljoyn.jar')),
                                        str(SmartHome_env.File('$DISTDIR/about/jar/alljoyn_about.jar')) ])
    SmartHome_env['dep_jars'] = [ '$DISTDIR/java/jar/alljoyn.jar',
                               '$DISTDIR/about/jar/alljoyn_about.jar' ]
else:
    SmartHome_env.Append(JAVACLASSPATH = [ str(SmartHome_env.File('$ALLJOYN_DISTDIR/java/jar/alljoyn.jar')),
                                        str(SmartHome_env.File('$ALLJOYN_DISTDIR/about/jar/alljoyn_about.jar')) ])
    SmartHome_env['dep_jars'] = [ ]

jars = []
jars += SmartHome_env.SConscript('src/SConscript', exports = ['SmartHome_env']),
if SmartHome_env['BUILD_SERVICES_SAMPLES'] == 'on':
    jars += SmartHome_env.SConscript('samples/SConscript', exports = ['SmartHome_env'])

SmartHome_env.Install('$DISTDIR/SmartHome/jar', jars)
